# Generated by go2rpm 1.15.0
%bcond check 1

# https://github.com/complytime/complytime
%global goipath         github.com/complytime/complytime
Version:                0.0.2

%gometa -L -f

%global common_description %{expand:
ComplyTime leverages OSCAL to perform compliance assessment activities, using
plugins for each stage of the lifecycle.}

Name:           complytime
Release:        %autorelease
Summary:        ComplyTime project

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT AND MPL-2.0
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools

Requires:  scap-security-guide

%description %{common_description}

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
# vendor/github.com/mattn/go-localereader has no license file
# %go_vendor_license_check -c %{S:2}
%if %{with check}
# gocheck failed at table_test.go
%gocheck -r *table_test.go
%endif

%files -f %{go_vendor_license_filelist}
%license vendor/modules.txt
%doc docs README.md cmd/openscap-plugin/README.md scripts/quick_start/README.md
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should not use globs to avoid installing conflicting
# binaries.
# Write a _bindir line per each of the binaries the package will install.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%{_bindir}/*


%changelog
%autochangelog
